// frontend/src/constants/products.ts
// Sample data — replace with backend/API data later

import type { ProductCard, ProductRowProps } from "@/types";

const CLOUDINARY_URL = "https://res.cloudinary.com/dl5ptl1zm/image/upload/v1774958962";

export const constructionProducts: ProductCard[] = [
  {
    id: "cement-opc-53",
    name: "OPC 53 Cement",
    nameLocal: "सिमेंट",
    image: `${CLOUDINARY_URL}/Cement_buxben.jpg`,
    description: "High-strength Ordinary Portland Cement, ideal for RCC work, columns, and slabs.",
    rating: 4.7,
    reviewCount: 128,
    unit: "per bag (50kg)",
    priceLabel: "₹380/bag",
    badge: "Best Seller",
    category: "construction",
  },
  {
    id: "plaster-of-paris",
    name: "Plaster of Paris",
    nameLocal: "प्लास्टर ऑफ पॅरिस",
    image: `${CLOUDINARY_URL}/PlasterOfParis_vldtbf.jpg`,
    description: "Smooth finish POP for wall plastering, ceiling work, and decorative mouldings.",
    rating: 4.3,
    reviewCount: 74,
    unit: "per bag (25kg)",
    priceLabel: "₹210/bag",
    category: "construction",
  },
  {
    id: "chuna-lime",
    name: "Hydrated Lime (Chuna)",
    nameLocal: "चुना",
    image: `${CLOUDINARY_URL}/HydratedLime_wipvwf.jpg`,
    description: "Pure hydrated lime for whitewashing walls, mortar mixing, and soil stabilisation.",
    rating: 4.1,
    reviewCount: 52,
    unit: "per bag (25kg)",
    priceLabel: "₹120/bag",
    badge: "Local Pick",
    category: "construction",
  },
  {
    id: "river-sand",
    name: "River Sand",
    nameLocal: "वाळू",
    image: `${CLOUDINARY_URL}/RiverSand_im1gyy.jpg`,
    description: "Clean, well-graded river sand for plastering, concrete mixing, and masonry work.",
    rating: 4.5,
    reviewCount: 96,
    unit: "per cubic ft",
    priceLabel: "₹55/cft",
    category: "construction",
  },
  {
    id: "red-brick",
    name: "Red Clay Bricks",
    nameLocal: "विटा",
    image: `${CLOUDINARY_URL}/RedClayBricks_khelaz.jpg`,
    description: "Machine-pressed red bricks with uniform size and high compressive strength.",
    rating: 4.6,
    reviewCount: 111,
    unit: "per 1000 pieces",
    priceLabel: "₹7,500/1000",
    badge: "Top Rated",
    category: "construction",
  },
  {
    id: "tmt-bars",
    name: "TMT Steel Bars",
    nameLocal: "लोखंडी सळई",
    image: `${CLOUDINARY_URL}/TMTSteelBars_k3rnp5.jpg`,
    description: "Fe-500 grade TMT bars for structural RCC work — earthquake resistant and rust-free.",
    rating: 4.8,
    reviewCount: 143,
    unit: "per kg",
    priceLabel: "₹68/kg",
    badge: "Premium",
    category: "construction",
  },
];

export const farmProducts: ProductCard[] = [
  {
    id: "wheat-lokwan",
    name: "Wheat (Lokwan)",
    nameLocal: "गहू (लोकवन)",
    image: `${CLOUDINARY_URL}/Wheat_nxbgrj.jpg`,
    description: "Premium Lokwan variety wheat directly from Buldhana farms — ideal for chakki flour.",
    rating: 4.6,
    reviewCount: 87,
    unit: "per quintal",
    priceLabel: "₹2,200/qtl",
    badge: "Fresh Harvest",
    category: "farm",
  },
  {
    id: "jowar-sorghum",
    name: "Jowar (Sorghum)",
    nameLocal: "ज्वारी",
    image: `${CLOUDINARY_URL}/Jowar_mujjoa.jpg`,
    description: "Traditional Vidarbha jowar — nutritious, gluten-free grain for bhakri and animal feed.",
    rating: 4.4,
    reviewCount: 63,
    unit: "per quintal",
    priceLabel: "₹1,900/qtl",
    badge: "Local Pick",
    category: "farm",
  },
  {
    id: "rice-hmt",
    name: "Rice (HMT)",
    nameLocal: "तांदूळ (HMT)",
    image: `${CLOUDINARY_URL}/Rice_vcoos6.jpg`,
    description: "Long-grain HMT rice known for its aroma and non-sticky texture. Farm-fresh from Akola.",
    rating: 4.7,
    reviewCount: 102,
    unit: "per quintal",
    priceLabel: "₹3,100/qtl",
    badge: "Best Seller",
    category: "farm",
  },
  {
    id: "tur-dal",
    name: "Tur Dal (Arhar)",
    nameLocal: "तूर डाळ",
    image: `${CLOUDINARY_URL}/TurDal_ximgn5.jpg`,
    description: "Sun-dried and cleaned toor dal, directly sourced from Vidarbha farmers.",
    rating: 4.5,
    reviewCount: 78,
    unit: "per kg",
    priceLabel: "₹140/kg",
    category: "farm",
  },
  {
    id: "cotton-kapas",
    name: "Raw Cotton (Kapas)",
    nameLocal: "कापूस",
    image: `${CLOUDINARY_URL}/Cotton_awnvup.jpg`,
    description: "High-quality raw cotton from Akola district — one of Maharashtra's finest cotton belts.",
    rating: 4.3,
    reviewCount: 45,
    unit: "per quintal",
    priceLabel: "₹6,800/qtl",
    badge: "Premium",
    category: "farm",
  },
  {
    id: "soyabean",
    name: "Soyabean",
    nameLocal: "सोयाबीन",
    image: `${CLOUDINARY_URL}/Soyabean_zuwfrq.jpg`,
    description: "Bold soybean seeds from Buldhana farms — high oil content, ideal for oil mills and dal.",
    rating: 4.2,
    reviewCount: 59,
    unit: "per quintal",
    priceLabel: "₹4,400/qtl",
    badge: "Fresh Harvest",
    category: "farm",
  },
];

export const productRows: ProductRowProps[] = [
  {
    title: "Construction Materials",
    titleLocal: "बांधकाम साहित्य",
    products: constructionProducts,
  },
  {
    title: "Farmer's Market",
    titleLocal: "शेतकरी बाजार",
    products: farmProducts,
  },
];
